import { createClient } from '@supabase/supabase-js';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Calendar, Search } from 'lucide-react';
import { notFound } from 'next/navigation';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

interface Props {
  params: Promise<{ session_id: string }>;
}

export default async function ReportPage({ params }: Props) {
  const { session_id } = await params;

  const { data, error } = await supabase
    .from('pipeline_runs')
    .select('*')
    .eq('session_id', session_id)
    .single();

  if (error || !data) notFound();

  const formattedDate = new Date(data.created_at).toLocaleString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return (
    <div className="flex-1 flex flex-col relative min-w-0 h-full">
      <header className="h-14 border-b border-neutral-800 bg-neutral-900/50 flex items-center px-6 backdrop-blur-sm z-10 w-full gap-3">
        <Link href="/" className="text-neutral-500 hover:text-white transition-colors">
          <ArrowLeft className="w-4 h-4" />
        </Link>
        <span className="text-neutral-700">/</span>
        <h1 className="text-sm font-medium text-neutral-400 truncate">
          Report — {data.keyword || 'Intelligence Report'}
        </h1>
      </header>

      <main className="flex-1 p-6 overflow-y-auto overflow-x-hidden w-full">
        <div className="max-w-4xl mx-auto">
          {/* Report header */}
          <div className="mb-8">
            <div className="flex items-center gap-2 text-xs text-neutral-500 mb-3">
              <Search className="w-3.5 h-3.5" />
              <span className="font-medium text-neutral-400">{data.keyword || 'Unknown keyword'}</span>
              <span className="text-neutral-700">·</span>
              <Calendar className="w-3.5 h-3.5" />
              <span>{formattedDate}</span>
            </div>
            <h1 className="text-2xl font-bold text-white mb-2">Intelligence Report</h1>
            <p className="text-neutral-400 text-sm">
              Market analysis and sales attack plan generated by the Marinduque OS pipeline.
            </p>
          </div>

          {/* Report body */}
          {data.combined_report ? (
            <article className="prose prose-invert prose-sm max-w-none prose-headings:text-white prose-p:text-neutral-300 prose-strong:text-emerald-300 prose-code:text-emerald-400 prose-hr:border-neutral-800 prose-li:text-neutral-300">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {data.combined_report}
              </ReactMarkdown>
            </article>
          ) : (
            <div className="text-neutral-500 text-sm italic">
              Report content is not available. The pipeline may still be processing.
            </div>
          )}

          {/* Footer links */}
          <div className="mt-12 pt-6 border-t border-neutral-800 flex items-center gap-6">
            <Link
              href="/hub"
              className="inline-flex items-center gap-2 px-5 py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white font-medium rounded-lg transition-all group"
            >
              Intelligence Hub
              <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </Link>
            <Link href="/" className="text-sm text-neutral-400 hover:text-white transition-colors">
              ← Run another pipeline
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}

export async function generateMetadata({ params }: Props) {
  const { session_id } = await params;
  const { data } = await supabase
    .from('pipeline_runs')
    .select('keyword')
    .eq('session_id', session_id)
    .single();

  return {
    title: data?.keyword ? `Report: ${data.keyword} — Marinduque OS` : 'Intelligence Report — Marinduque OS',
  };
}

